# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/worker_bee.rb'

Hoe.new('WorkerBee', Workerbee::VERSION) do |p|
  # p.rubyforge_name = 'WorkerBeex' # if different than lowercase project name
  p.developer('Mathew Chasan', 'aftermathew@gmail.com')
end

# vim: syntax=Ruby
